sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - rustc --verbose --version
  - cargo --version
branches:
  only:
    - master
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc --no-deps &&
  echo "<meta http-equiv=refresh content=0;url=twitch_client/index.html>" > target/doc/index.html &&
  git clone https://github.com/davisp/ghp-import &&
  ./ghp-import/ghp_import.py -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    - secure: gu0AUtK6+HdKGp6090ZmSgKvf4d+AtatarKp9XTLgEothHxVtSZiQf5QZQJm2fwGh492ezqr1XkVmcs7Pq6Wpre0bKeQCJQQ5Ch5CTIlwhxXY1E0VvEihMngOOlWd8bf6YDVNyPCZu7E6sdWQzfzxFJIZCsKDw89eBIbDpxeVRaSFVpi/krBoB9ImgbBaaM/N74VvaS3Fx2nSpCd5oe8Q1wyinZBeAWAqmR00mOx/PHyLkxBta0fDsLzDiD3JxT6MrxL4ooF8Xyzs4iMvDwK9JjiQhnawvzKQiQ8qrCCdLrlF6CTcBjizzZJgda3FfoYJRAQZtBJF4np5cjMrQ/GpptyjKldDUxn5MyA1TS0RgvCz2iB7nE91euNjX1Y8QMmTxtJD/KlmT9ya4b50T9F2wYZH/jXuhCueuHVKjPrGAnDRj68n3RMW/lTecig1JPyYRSkCULRBdvwONZ7KmLqTNVlM0/6i2esoLrsecS5Vr7ZXSDC7VkGiaLdoyvt1Es0oIVfBNcIJ7dI1c8t9bAV40/vs3a+80d+YsHu1VZKhullSJAtzdY5bzNcmSfrkk8p7NS5iKmZHed1bVgIeobm5wV4eSPZ2Bfa5KzLmoSYVRSOPZdLJNev8HhRiCTj3URAR9WE2IGa7NAahYeyVTR/X2+873FC9+6v8PI76a2BpG0=
    - secure: dNEAJhHC8GdaCAMcX/h07qZiuWpUWKw9hB3utazgVT+e0WJfWRvW4TmXZeWKignK/pmONoynWzG4o7VpZlNP6hTMuIh0cXIKykdSeV+J/JXMjYT7QMnyTOl6hKJok1O5aCvMoAHCozqE0zPe/eBaffNr0LIoKBbUM6A69IGaip7RDNw9RIGw9A+lM5GnXL7fHRGxl5Vupr1fImSpdLlUHuJCZpV1uQtjIC/2xJ0hhx2aG3bWvC8m2mtSls1y64TV/6poAT4h9PM9+B5Mx+xTwKpulA0sKB1AZcjPYwI/jEm00ov7l73m42PLuHsf+OUAx1/YfpaUMb4LGP/8KxTHA+wtZfNi2IpIifwDR8P57F8H5cEEFNskVSEXigGGdsNubFZB1BHgl4M5cy+wDk+SIAt5x99Xju5ciglfb48WHMJQ+CwxLVbKUuGfw93aJvBtIeVsQbBvH8x8MiABwfLhMGwepDnnNH50DHpajA61cZYfz4x8/lzaumcr7blw8R7RIJg0/eNhgSgtd5Uqd+m/3XxU9JkQQVYZYmjV4cCpp5iZ2PSj+o3NyWfD89lxWvJ8RYf14pUTUkSeqP9pur4ljs/JGbbhw2+FoxVF9dtMLgh4KCX3/LlzlF7a9i92n3Sz3Hu008lp39Eqi+tq5U3dm/8vaUoKLidSyU7X/z2plCw=
