[package]
name = "twitch-client"
version = "0.1.0"
description = "Twitch REST API client"
license = "MIT/Apache-2.0"
authors = ["Michael Mitteregger <michael.mitteregger@gmx.at>"]
keywords = ["twitch"]

[dependencies]
hyper = "0.7.2"
serde = "*"
serde_json = "*"
serde_macros = "*"
